
CREATE TABLE PRODUTO
(
ID_PROD INT NOT NULL IDENTITY(1,1), 
NOM_PROD VARCHAR(255) NOT NULL,
VL_VEND DECIMAL(18,2) NOT NULL, 
DESC_PROD VARCHAR(255) NULL,
STR_IMAG VARBINARY(MAX),
DT_INCLUSAO DATETIME,
DT_ALTERACAO DATETIME,
FLG_SITUACAO BIT
)
ALTER TABLE PRODUTO ADD CONSTRAINT PK_PRODUTO PRIMARY KEY (ID_PROD)
ALTER TABLE PRODUTO ADD CONSTRAINT DF_PRODUTO_DT_INCLUSAO   DEFAULT GETDATE() FOR DT_INCLUSAO
ALTER TABLE PRODUTO ADD CONSTRAINT DF_PRODUTO_FLG_SITUACAO   DEFAULT 1 FOR FLG_SITUACAO

INSERT INTO PRODUTO (NOM_PROD, VL_VEND, DESC_PROD, STR_IMAG ) VALUES ('Pizza de queijo', 34.00, 'Pizza sabor muito queijo', CONVERT(VARBINARY,''))
INSERT INTO PRODUTO (NOM_PROD, VL_VEND, DESC_PROD, STR_IMAG ) VALUES ('Lanche', 88.00, 'Lanche especial', CONVERT(VARBINARY,''))
